### ISSUE TITLE
How to set range of number in FF1  to get min and max range

### ISSUE THREAD

**Issue by rajatjhaexate** [a-tze/FPE.Net#1]
Hi @a-tze  thank you for you're awesome code 
please solve my issue for input number min max range in decrypt number 
thank you

**Comment by a-tze** [comment]
As explained in the README, the range of numbers is always between 0 and radix-1.

If your issue is something different, please explain in more detail.

**Comment by rajatjhaexate** [comment]
Hi @a-tze 
we are facing issue range on 0 we want increase min range

**Comment by a-tze** [comment]
It is a substantial property of the algorithm that the range starts at zero. If you cannot apply subtraction and addition to the cleartext numbers, you have to use something different.

**Comment by rajatjhaexate** [comment]
ok thank you
